#!/usr/bin/env bash
# This script Manages the script manage_my_process.
# When passed the argument `start`:
#  A. Starts manage_my_process
#  B. Creates a file containings its PID in /var/run/my_process.pid
#  C. Displays "manage_my_process started"
# When passed the argument `stop`:
#  A. Stops manage_my_process
#  B. Deletes the file /var/run/my_process.pid
#  C. Displays "manage_my_process stopped"
# When passed the argument `restart`:
#  A. Stops manage_my_process
#  B. Deletes the file /var/run/my_process.pid
#  C. Starts manage_my_process
#  D. Creates a file containing its PID in /var/run/my_process.pid
#  E. Displays "manage_my_process restarted"
# If any other or no arguments are passed, displays "Usage: manage_my_process {start|stop|restart}"
if [ "$1" == "start" ]
then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
  kill "$(pgrep -f /manage_my_process)" 
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process restarted"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
