#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd.
file_path="/etc/passwd"
if [ -e "$file_path" ]; then
    while IFS=: read -r username passwd uid gid info home shell; do
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $info"
    done < "$file_path"
else
    echo "Error: $file_path does not exist."
fi
