#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
counter=1
while [ "$counter" -lt 21 ]; do
    case "$counter" in
	5)
	    echo "bad luck from China"
	    echo "$counter"
	    ;;
	10)
	    echo "bad luck from Japan"
	    echo "$counter"
	    ;;
	18)
	    echo "bad luck from Italy"
	    echo "$counter"
	    ;;
	*)
	    echo "$counter"
	    ;;
    esac
    ((counter++))
done
