#!/usr/bin/env bash
# This script display the content of the current directory in a list format
for file in *; do
    if [ -f "$file" ] && [[ $file =~ ^[0-9]+-(.+) ]]; then
        echo "${BASH_REMATCH[1]}"
    fi
done
